- name: configure front end server
  become: yes
  hosts: frontend
  tasks:
  - name: installing nginx
    ansible.builtin.dnf:
     name: nginx
     state: installed

  - name: start and enable nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes
  
  - name: remove the index files
    ansible.builtin.file:
     path: /usr/share/nginx/html
     state: absent


  - name: creating the directories
    ansible.builtin.file:
     path: /usr/share/nginx/html
     directory: present

